---

  - set_fact:
      _cur_seccfg: >-
        {{ _iter_secrets.value.config | combine({'key': _iter_seckeys}) }}

  - name: read secret
    terryhowe.hashivault.hashivault_read: >-
      {{ _cur_seccfg }}
    register: _tmp_modres


    # update result var with new secret value
  - set_fact:
      smabot_hashivault_read_secrets: >-
        {{ smabot_hashivault_read_secrets
         | combine({
             _cur_seccfg.mount_point: {
                 _cur_seccfg.secret: {
                     _cur_seccfg.key: _tmp_modres.value
                 }
             }
           }, recursive=True, list_merge='append')
        }}

