---

## TODO: support reading all secrets and regex matching secrets

## TODO: default to all subkeys when no specific key list is specified

  - include_tasks: read_secret.yml
    loop: >-
      {{ _iter_secrets.keys }}
    loop_control:
      loop_var: _iter_seckeys

