---

  - name: replace project deploy key in gitserver  ==>>  {{ _secretcycle_parent_iter.key }}/{{ _secretcycle_cycle_iter.key }}/{{ _secretcycle_subjects_iter.value.name }}
    smabot.gitlab.modwrap:
##modname: gitlab_deploy_key_dbg
      modname: gitlab_deploy_key
      modargs:
        project: "{{ _secretcycle_subjects_iter.value.name }}"
        title: >-
           {{ _secretcycle_subjects_iter.value.keytitle 
            | default('autocycle_default', True) }}
        state: present
        key: "{{ _tmp_hvault_data['/public'].public_key }}"

