---
 
  - include_tasks: handle_policies.yml
    loop: >-
      {{ smabot_hashivault_config_instance_args_normed.policies.source_dirs.dirs
       | dict2items }}
    loop_control:
      loop_var: _iter_poldirs


  ## manage auth methods
  - include_tasks: handle_auth_methods/main.yml
    loop: >-
      {{ smabot_hashivault_config_instance_args_normed.auth_methods.authers
       | dict2items }}
    loop_control:
      loop_var: _iter_auth_methods


  - name: collect metadata about all defined auth methods
    terryhowe.hashivault.hashivault_auth_list:
    register: _tmpres_authlist

  - set_fact:
      _hvault_authmeths: >-
        {{ _tmpres_authlist.backends }}


  ## update visible policies to all currently defined ones
  - set_fact:
      _hvault_poll_policies: True
      _hvault_match_policies: False

  - include_tasks: get_matching_policies.yml


  ## manage approlers, but only the ones necessary pre login (vault managers)
  - include_tasks: handle_approlers.yml
    loop: >-
      {{ [smabot_hashivault_config_instance_args_normed.approlers._vaultman] }}
    loop_control:
      loop_var: _iter_approlers
    when: smabot_hashivault_config_instance_args_normed.approlers._vaultman is truthy

