---

  - include_tasks: handle_policy.yml
    loop: >-
      {{ query('community.general.filetree', _iter_poldirs.value.path)
       | smabot.hashivault.policies_from_files(
           policy_cfg=smabot_hashivault_config_instance_args_normed.policies,
           dircfg=_iter_poldirs.value
       ) }}
    loop_control:
      loop_var: _iter_policies

