---

  - name: login to vault / aquire auth token
    smabot.hashivault.hashivault_login:
      authtype: approle
      login_mount_point: "{{ _vaultman_creds.login_mount }}"
      role_id: "{{ _vaultman_creds.id }}"
      secret_id: "{{ _vaultman_creds.secret }}"
      url: "{{ _vault_env.VAULT_ADDR }}"
    register: _tmp_login
    no_log: true

  - set_fact:
      _vault_env: >-
        {{ _vault_env | combine({'VAULT_TOKEN': _tmp_login.login.token}) }}
    no_log: true

