---

  ##
  ## note that while most config stuff can be done on from any
  ## node using vault rest api's this initial configuration
  ## must be absolutely done from the same system vault is running
  ##

  - include_tasks: prepare_system.yml

  - name: "initialize hashicorp vault server"
    smabot.hashivault.config_initializer: >-
      {{ smabot_hashivault_config_initial_args | default(omit, True) }}
    register: smabot_hashivault_init_state
    no_log: true


##  - debug:
##      var: hashivault_init_state


  - set_fact:
      smabot_hashivault_first_init: >-
        {{ smabot_hashivault_init_state.get('key_setup', {}).get('root_token', None)
         | smabot.base.to_bool }}

