---

  - set_fact:
      _tmp_hvault_params2: >- 
        {{ _tmp_hvault_params | combine({
            'secret': _tmp_hvault_params.secret + _multipath_iter.key}) 
        }}


  - block:

        ##
        ## note: it seems impossible to use stuff from a classical role inside a collection (at least if this role is not inside galaxy and awx is used), I at least tried a lot and nothing worked
        ##
      - name: read current secret from hashivault  ==>>  {{ _secretcycle_parent_iter.key ~ '/' ~ _secretcycle_cycle_iter.key ~ '/' ~ _secretcycle_subjects_iter.value.name ~ _multipath_iter.key }}
        smabot.hashivault_modules.hashivault_read: "{{ _tmp_hvault_params2 }}"
        ##terryhowe.hashivault_read: "{{ _tmp_hvault_params }}"
        ##terryhowe.hashivault.hashivault_read: "{{ _tmp_hvault_params }}"
        ##terryhowe.ansible-modules-hashivault.hashivault_read: "{{ _tmp_hvault_params }}"
        ##terryhowe.ansible_modules_hashivault.hashivault_read: "{{ _tmp_hvault_params }}"
        no_log: true
        register: _tmp_res
        ##register: "{{ '_tmp_hvault_cur_secret_' ~ _multipath_iter.key }}" ## note: it seems templating is not allowed in register

      - set_fact:
          _tmp_hvault_cur_secret: >-
             {{ _tmp_hvault_cur_secret | default({}, True) 
              | combine({ _multipath_iter.key: _tmp_res.value }) }}

        no_log: true

    rescue:

      - name: check if read error is unset error       
        set_fact:
          _secret_unset: >-
            _tmp_res.msg is 
              search("Secret .* is not in vault", ignorecase=True) 


      - name: fail because of generic vault read error
        ansible.builtin.fail:
          msg: >-
            Reading secret from hashivault failed:
            {{ _tmp_res.msg }}

        when: not _secret_unset


      - name: fail because of vault unset error not allowed
        ansible.builtin.fail:
          msg: >-
            Secret does not exist yet inside hashivault, either 
            initialise this secret before using the cycler or 
            set the config option "unset_ok" for this cycler

        when: not _secretcycle_subjects_iter.value.unset_ok

