---

  - set_fact:
      _tmp_hvault_params2: >- 
         {{ _tmp_hvault_params | combine({ 
              'data': _tmp_hvault_data[_multipath_iter.key],
              'secret': _tmp_hvault_params.secret + _multipath_iter.key
            })
         }}
    no_log: true


  - name: write back secret to hashivault  ==>>  {{ _secretcycle_parent_iter.key ~ '/' ~ _secretcycle_cycle_iter.key ~ '/' ~ _secretcycle_subjects_iter.value.name ~ _multipath_iter.key }}
    smabot.hashivault_modules.hashivault_write: "{{ _tmp_hvault_params2 }}"

