---

  - name: replace user key in gitserver  ==>>  {{ _secretcycle_parent_iter.key }}/{{ _secretcycle_cycle_iter.key }}/{{ _secretcycle_subjects_iter.value.name }}
    smabot.git.gitlab_user_sshkeys:
      user: "{{ _secretcycle_subjects_iter.value.name }}"
      pubkey: "{{ _tmp_hvault_data['/public'].public_key }}"
      keytitle: >-
         {{ _secretcycle_subjects_iter.value.keytitle 
          | default('autocycle_default', True) }}

