---

  - set_fact:
      _tmp_hvault_data:
        /private:
          ## 
          ## note: even if not really needed by the workflow, 
          ##   this is atm a mandatory subkey for jenkins vault plugin
          ## 
          user: "{{ _tmp_hvault_cur_secret['/private'].user }}"

          ##
          ## note: the extra newline add the end is mega important, 
          ##   otherwise one can get weird errors when calling ssh-add 
          ##   or similar complaining about invalid key format
          ##
          private_key: "{{ _tmp_hvault_cur_secret['/private'].private_key }}"

          ## 
          ## note: this is also mandatory for jenkins atm, 
          ##   but it seems to be fine if it is empty
          ## 
          passphrase: "{{ _tmp_hvault_cur_secret['/private'].passphrase }}"

        /public:
          public_key: "{{ _tmp_hvault_cur_secret['/public'].public_key }}"

    no_log: true

