---

  - name: set new random password  ==>>  {{ _secretcycle_parent_iter.key }}/{{ _secretcycle_cycle_iter.key }}/{{ _secretcycle_subjects_iter.value.name }}
    smabot.windows.update_adpw:
        ## auth params, principal mandatory but fillable from ansible vars / env
        server: "{{ _secretcycle_parent_iter.value.url }}"
        domain: "{{ _secretcycle_parent_iter.value.domain }}"
        base_dn: "{{ _secretcycle_parent_iter.value.base_dn }}"

        auth_user: "{{ _tmp_hvault_cur_secret[''].user }}"
        auth_pw: "{{ _tmp_hvault_cur_secret[''].password }}"

        pw_new: "{{ _tmp_new_pw }}"
  
        ## optional, if unset auth user creds are used
        ##user: haha
        ##pw_old: foo

