---

  - name: generate new random password  ==>>  {{ _secretcycle_parent_iter.key }}/{{ _secretcycle_cycle_iter.key }}/{{ _secretcycle_subjects_iter.value.name }}
    set_fact:
      _tmp_new_pw: >-
        {{ lookup('password', 
             '/dev/null length=' ~ _secretcycle_cycle_iter.value.pwlen )
        }}
    no_log: true


  - set_fact:
      _tmp_hvault_data:
        "":
          user: "{{ _tmp_hvault_cur_secret[''].user }}"
          password: "{{ _tmp_new_pw }}"
    no_log: true

