---

  - set_fact:
      _tmp_hvault_data: >-
        {{ { "": {
          'user': _tmp_hvault_cur_secret[''].user,
          'password': _tmp_hvault_cur_secret[''].password,
        } } }}
    no_log: "{{ not (disable_secret_log_hiding | default(false, True)) }}"

