---

  - name: update gitlab user token  ==>>  {{ _secretcycle_parent_iter.key }}/{{ _secretcycle_cycle_iter.key }}/{{ _secretcycle_subjects_iter.value.name }}
    smabot.git.gitlab_user_tokens:
      ## default "present" makes sure that the tokens exist 
      ## (creates if new), but is a green noop if such a token 
      ## already exists while update always recreates it
      state: update

      user: "{{ _secretcycle_subjects_iter.value.user }}"

      ## dict of tokens to manage
      user_tokens: >-
        {{ { _secretcycle_subjects_iter.value.name: 
          (_secretcycle_subjects_iter.value.config | default(omit)) } }}

    register: _tmp_new_token
    no_log: "{{ not (disable_secret_log_hiding | default(false, True)) }}"


  - set_fact:
      _tmp_hvault_data: >-
        {{ { '': {
          'user': _secretcycle_subjects_iter.value.user,
          'token': _tmp_new_token.user_tokens[_secretcycle_subjects_iter.value.name].token 
        } } }}
    no_log: "{{ not (disable_secret_log_hiding | default(false, True)) }}"

