---

  - set_fact:
      _modcfg: >-
        {{ _iter_oidc_backend_role.config }}


    ## optionally when requested directly attach policies to backend roles
  - block:

      - set_fact:
          _hvault_poll_policies: False
          _hvault_match_policies: True
          _hvault_pol_selector: >-
             {{ _iter_oidc_backend_role.policies }}

      - include_tasks: get_matching_policies.yml


      - set_fact:
          _modcfg: >-
            {{ _modcfg
             | combine({
                 'token_policies': _hvault_matching_pols,
             })
            }}

    when: _iter_oidc_backend_role.policies


  - name: create or delete oidc backend role
    terryhowe.hashivault.hashivault_oidc_auth_role: >-
      {{ _modcfg }}

