---

  - set_fact:
      smabot_hashivault_readwrite_secrets_args: >-
        {{ _iter_upd_creds.params
         | smabot.hashivault.convert_update_creds_params(
             upload_creds=smabot_upload_creds,
             config=_iter_upd_creds,
             mode=_smabot_hashivault_upd_creds_mode
           )
        }}
    ##no_log: true

  - block:

      - name: read current / old secret from hashivault  ==>>  {{ _cur_roler.name }}
        ansible.builtin.include_role:
          name: smabot.hashivault.readwrite_secrets


      - set_fact:
          _smabot_hashivault_old_secret: >-
             {{ smabot_hashivault_read_secrets | first }}
        when: smabot_hashivault_read_secrets | default(False)
        no_log: true

    when: _smabot_hashivault_upd_creds_mode == 'read'


  - name: write back updated credentials to hashivault  ==>>  {{ _cur_roler.name }}
    ansible.builtin.include_role:
      name: smabot.hashivault.readwrite_secrets
    when: _smabot_hashivault_upd_creds_mode == 'write'

